### ISSUE TITLE
Fonts in docs

### ISSUE THREAD

**Issue by cormullion** [neelsmith/BiblicalHebrew.jl#1] opened 2023-12-07 21:36 UTC
Hi! As I think you know, the font JuliaMono's support for Hebrew (and Arabic) is incomplete - not yet finished. I've been planning to work on it for a while now, but it's not been a priority, and in any case it wouldn't be available any time soon.

Until then, I'd recommend using a custom CSS theme file and find a font with no (or full) support for Hebrew. (I used to do this in [reverse](https://github.com/JuliaGraphics/Luxor.jl/blob/d131046d194d28e43c365442efdb7d825c028251/docs/src/assets/themes/documenter-dark.css#L1).)

You probably already know this, anyway. 😂

Good luck!

**Comment by neelsmith** [comment] 2023-12-09 18:44
One easy workaround that I've just discovered (don't understand *why* it works, but it does...) is to pipe a string through `Markdown.parse` as the final value for a `Documenter` code block.

I'm going to update all the documentation here to work that way, and when I've verified the results, will close this issue.

Thank you for your helpful suggestions.

**Comment by neelsmith** [comment] 2023-12-10 21:24
The issue is with the fonts `Documenter` uses for code blocks.  Piping code through `Markdown.parse` gets a font that covers the full Hebrew range of Unicode.  Closing this issue.

**Closed as completed by neelsmith** 2023-12-10 21:24 UTC
